[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisor/supervisord.pid
childlogdir=/var/log/supervisor

[unix_http_server]
file=/var/run/supervisor/supervisor.sock
chmod=0700

[supervisorctl]
serverurl=unix:///var/run/supervisor/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:airflow-webserver]
command=airflow webserver --port 8080
directory=/app
autostart=true
autorestart=true
startretries=3
stderr_logfile=/app/airflow/logs/webserver/webserver.err.log
stdout_logfile=/app/airflow/logs/webserver/webserver.out.log
priority=100

[program:airflow-scheduler]
command=airflow scheduler
directory=/app
autostart=true
autorestart=true
startretries=3
stderr_logfile=/app/airflow/logs/scheduler/scheduler.err.log
stdout_logfile=/app/airflow/logs/scheduler/scheduler.out.log
priority=200

[program:airflow-worker]
command=airflow celery worker
directory=/app
autostart=true
autorestart=true
startretries=3
stderr_logfile=/app/airflow/logs/worker/worker.err.log
stdout_logfile=/app/airflow/logs/worker/worker.out.log
priority=300

[program:airflow-triggerer]
command=airflow triggerer
directory=/app
autostart=true
autorestart=true
startretries=3
stderr_logfile=/app/airflow/logs/triggerer/triggerer.err.log
stdout_logfile=/app/airflow/logs/triggerer/triggerer.out.log
priority=400